; This is your license Key *** valid only for this computer ***
;--------------------------------------------------
; WARNING: If you modify your license key, Task Automator wont be able to validate your copy.
;--------------------------------------------------
[Data]
LicenseKey=
