; This is your license Key *** valid only for this computer ***
; ADVISE: Set this file as Read Only for extra security.
; WARNING: If you modify your license key, Task Automator wont be able to validate your copy.
[Data]                                  
LicenseKey=N.:$*'.H(4063!<B?396[K+7N.:@H(46<9\<B?H(4
