;--------------------------------------------------
; This is your license Key *** valid only for this computer ***
; The standard License amount allowed is up to 3 devices
;--------------------------------------------------
; WARNING: If you modify your license key, Task Automator wont be able to
; validate your copy and will prompt you to register or login.
;--------------------------------------------------
; The data stored here is not sensitive and even if its somehow stolen 
; it wont work on any other device.
;--------------------------------------------------
; All data shown here is informative. Yes, even if you modifify the licenseAmount 
; the app still checks its real value on the database.
;--------------------------------------------------
[Data]
LicenseKey=
UserName=
LicenceAmount=
DeviceNumber=
