;--------------------------------------------------
; NOTE: For all numpad keys, verify that NumLock key is activated / deactivated in order to trigger them.
;--------------------------------------------------
; HINT: If you delete this file or move it away from its forder,
; Task Automator will generate a new file on the spot.
;--------------------------------------------------
; WARNING 1: When asigning hotkeys, make sure none of them are the same as other asigned hotkeys.
;--------------------------------------------------
; WARNING 2: Don't set this file as read only!
;--------------------------------------------------
[Modules]
SwitchJumps=0
SwitchClicker=0
QuickAccess=1
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
SecureMode=1
EditBoxesAvailable=1
SuspendHotkeys=0
AutoRunLoop=100
GeneralLoopInterval=100
LoopAmount=100
;--------------------------------------------------
[PaceProperties]
ScrlUpCount=33
ScrlUpInterval=150
ScrlDownCount=33
ScrlDownInterval=150
;--------------------------------------------------
[SavedHotkey]
StartAutoRunHotkey=r
StopAutoRunHotKey=t
PatternClickerHotkey=Numpad8
StopPatternHotkey=Numpad9
;-------------------------------
JumpHotkey0=Numpad0
JumpHotkey1=Numpad1
JumpHotkey2=Numpad2
JumpHotkey3=Numpad3
JumpHotkey4=Numpad4
;-------------------------------
QuickAccessHk1=1
QuickAccessHk2=2
QuickAccessHk3=3
QuickAccessHk4=4
QuickAccessHk5=5
QuickAccessHk6=6
QuickAccessHk7=7
QuickAccessHk8=8
QuickAccessHk9=9
;--------------------------------------------------
[AutoRun]
SprintKey=Shift
;--------------------------------------------------
[AutoRunKeyboard]
ForwardKey=w
;--------------------------------------------------
[AutoRunController]
ButtonRT=w
;--------------------------------------------------
[AutoClicker]
ClickInterval=50
RandomOffset=50
;--------------------------------------------------
[CursorLocationClicker]
CoordX0=950
CoordY0=240
Coord0Interval=1000
;-------------------------------
CoordX1=950
CoordY1=770
Coord1Interval=1000
;-------------------------------
CoordX2=840
CoordY2=474
Coord2Interval=1000
;-------------------------------
CoordX3=1076
CoordY3=474
Coord3Interval=1000
;-------------------------------
CoordX4=949
CoordY4=463
Coord4Interval=1000
;--------------------------------------------------
[QuickAccessPath]
QuickAccess1=https://mean-littles-app.gitbook.io/mean-littles-software
QuickAccess2=https://cornucopias.io/
QuickAccess3=C:\Users\
QuickAccess4=https://outlook.live.com/mail/
QuickAccess5=https://drive.google.com/drive/
QuickAccess6=
QuickAccess7=
QuickAccess8=
QuickAccess9=
;--------------------------------------------------
[QuickAccessIcons]
QuickIcon1=
QuickIcon2=
QuickIcon3=
QuickIcon4=
QuickIcon5=
QuickIcon6=
QuickIcon7=
QuickIcon8=
QuickIcon9=
;--------------------------------------------------
[JumpProperties]
VeryShortJumpRace=400
VeryShortJumpLenght=500
;-------------------------------
ShortJumpRace=550
ShortJumpLenght=500
;-------------------------------
NormalJumpRace=550
NormalJumpLenght=600
;-------------------------------
LongJumpRace=550
LongJumpLenght=700
;-------------------------------
VeryLongJumpRace=600
VeryLongJumpLenght=750
