; ------------ Credits ------------
; Creator: Fernando Daniel Jaime.
; Programmer Alias: FDJ-Dash.
; Gamer Alias: Mean Little, Grey Dash, Dash.
; ------------ App Details ------------
; App Full Name: Mean Little's Task Automator.
; Description: This is an app aimed towards repetitive tasks like holding a
; button down for extended time, mouse clicks or even click patterns.
; Additionally, it brings interchangeable modules like jumps for certain
; games and Quick access module to store and run any program in your computer
; or load a web page on your browser easily.
;--------------------------------------------------
; NOTE: For all numpad keys, verify that NumLock key is activated / deactivated in order to trigger them.
;--------------------------------------------------
; HINT: If you delete this file or move it away from its forder,
; Task Automator will generate a new file with dafault values on the spot.
;--------------------------------------------------
; ADVISE: If you need to use a specific Module, its a good idea to turn all 
; other modules OFF from the Options menu bar.
;--------------------------------------------------
; Find the list of key names here: https://www.autohotkey.com/docs/v2/KeyList.htm
;-------------------------------
; See the list of recommended fonts here: https://www.autohotkey.com/docs/v2/misc/FontsStandard.htm
;-------------------------------
; See the list of color names and RGB values here: https://www.autohotkey.com/docs/v2/misc/Colors.htm
; Black Silver Gray White Maroon Red Purple Fuchsia Green Lime Olive Yellow Navy Blue Teal Aqua
; If the color name you need is not listed you can still write its RGB value
;--------------------------------------------------
[Modules]
SwitchKbAutoRun=1
SwitchControllerAutoRun=1
SwitchTopModulesOFF=1
;-------------------------------
SwitchQuickAccess=0
QuickAccessButtons=1
SwitchClicker=1
SwitchJumps=0
SwitchModulesOFF=0
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
SuspendedHotkeysTimeWait=1000
HotkeyEditMode=1
EditBoxesAvailable=1
AutoRunLoopInterval=100
GeneralLoopInterval=100
LoopAmount=100
GuiPriorityAlwaysOnTop=0
;-------------------------------
PositionX=1285
PositionY=103
;-------------------------------
ExitTaskAutomatorKey=Esc
SuspendHotkeysKey=Enter
;--------------------------------------------------
[Settings]
CheckforUpdatesDaily=1
CheckforupdatesWeekly=0
NeverCheckForUpdates=0
NeedUpdate=0
;-------------------------------
LastUpdateCheckTimeStamp=20250126221904
;--------------------------------------------------
[PaceProperties]
ScrlUpCount=33
ScrlUpInterval=150
ScrlDownCount=33
ScrlDownInterval=150
;--------------------------------------------------
[SavedHotkey]
StartAutoRunHotkey=r
StopAutoRunHotKey=t
;-------------------------------
PatternClickerHotkey=Shift
;-------------------------------
JumpHotkey0=Numpad0
JumpHotkey1=Numpad1
JumpHotkey2=Numpad2
JumpHotkey3=Numpad3
JumpHotkey4=Numpad4
;-------------------------------
QuickAccessHk1=1
QuickAccessHk2=2
QuickAccessHk3=3
QuickAccessHk4=4
QuickAccessHk5=5
QuickAccessHk6=6
QuickAccessHk7=7
QuickAccessHk8=8
QuickAccessHk9=9
;--------------------------------------------------
[AutoRun]
SprintKey=Shift
;--------------------------------------------------
[AutoRunKeyboard]
ForwardKey=w
;--------------------------------------------------
[AutoRunController]
ButtonRT=w
;--------------------------------------------------
[AutoClicker]
ClickInterval=50
RandomOffset=50
;--------------------------------------------------
[CursorLocationClicker]
CoordX0=950
CoordY0=240
Coord0Interval=450
;-------------------------------
CoordX1=950
CoordY1=770
Coord1Interval=450
;-------------------------------
CoordX2=840
CoordY2=474
Coord2Interval=450
;-------------------------------
CoordX3=1076
CoordY3=474
Coord3Interval=450
;-------------------------------
CoordX4=949
CoordY4=600
Coord4Interval=450
;-------------------------------
CoordX5=698
CoordY5=336
Coord5Interval=450
;-------------------------------
CoordX6=854
CoordY6=175
Coord6Interval=450
;--------------------------------------------------
[QuickAccessPath]
QuickAccess1=https://mean-littles-app.gitbook.io/mean-littles-software
QuickAccess2=https://cornucopias.io/
QuickAccess3=C:\Users\
QuickAccess4=https://outlook.live.com/mail/
QuickAccess5=https://drive.google.com/drive/
QuickAccess6=
QuickAccess7=
QuickAccess8=
QuickAccess9=
;--------------------------------------------------
[QuickAccessIcons]
QuickIcon1=
QuickIcon2=
QuickIcon3=
QuickIcon4=
QuickIcon5=
QuickIcon6=
QuickIcon7=
QuickIcon8=
QuickIcon9=
;--------------------------------------------------
[JumpProperties]
VeryShortJumpRace=400
VeryShortJumpLenght=500
;-------------------------------
ShortJumpRace=550
ShortJumpLenght=500
;-------------------------------
NormalJumpRace=550
NormalJumpLenght=600
;-------------------------------
LongJumpRace=550
LongJumpLenght=700
;-------------------------------
VeryLongJumpRace=600
VeryLongJumpLenght=750
;--------------------------------------------------
[FontType]
MainFontType=Comic Sans MS
MessageAppNameFontType=Georgia
LicenseKeyFontType=Comic Sans MS
MessageMainMsgFontType=Georgia
MessageFontType=Georgia
;--------------------------------------------------
[FontColors]
MainFontColor=Lime
FontClickerPatternColor=70A0FA
;-------------------------------
MessageAppNameFontColor=Lime
LicenseKeyFontColor=70A0FA
MessageMainMsgFontColor=Lime
MessageFontColor=Lime
;--------------------------------------------------
[Background]
BackgroundColor=2F2F2F
BackgroundPicture=
MessageBackgroundPicture=
;--------------------------------------------------
[Pictures]
TopPicture=
BottomPicture=
