; ------------ Credits ------------
; Creator: Fernando Daniel Jaime.
; Programmer Alias: FDJ-Dash.
; ------------ App Details ------------
; App Name: Task Automator.
;--------------------------------------------------
; Description: This is an app aimed towards repetitive tasks like holding a
; button down for extended time, mouse clicks or even click patterns.
; Additionally, it brings interchangeable modules like jumps for certain
; games and Quick access module to store and run any program in your computer
; or load a web page on your browser easily.
;--------------------------------------------------
; NOTE: For all numpad keys, verify that NumLock key is activated / deactivated in order to trigger them.
;--------------------------------------------------
; HINT: If you delete this file or move it away from its folder,
; Task Automator will generate a new file with dafault values on the spot.
;--------------------------------------------------
; Listed colors:
; Black Silver Gray White Maroon Red Purple Fuchsia Green Lime Olive Yellow Navy Blue Teal Aqua
; If the color name you need is not listed you can still write its RGB value.
;--------------------------------------------------
[FontType]
MainFontType=Comic Sans MS
MessageAppNameFontType=Georgia
LicenseKeyFontType=Comic Sans MS
MessageMainMsgFontType=Georgia
MessageFontType=Georgia
;--------------------------------------------------
[FontColors]
MainFontColor=Lime
FontClickerPatternColor=70A0FA
;----------
MessageAppNameFontColor=Lime
LicenseKeyFontColor=70A0FA
MessageMainMsgFontColor=Lime
MessageFontColor=Lime
;--------------------------------------------------
[Background]
BackgroundColor=2F2F2F
BackgroundPicture=
MessageBackgroundPicture=
;--------------------------------------------------
[Modules]
SwitchKbAutoRun=1
SwitchControllerAutoRun=0
SwitchQuickAccess=0
QuickAccessButtons=0
SwitchClicker=0
SwitchJumps=0
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
SuspendedHotkeysTimeWait=1000
SaveSuccesfullTimeWait=1000
;----------
AutoRunLoopInterval=100
GeneralLoopInterval=100
LoopAmount=100
GuiPriorityAlwaysOnTop=1
;----------
PositionX=1263
PositionY=190
;----------
ExitTaskAutomatorKey=Esc
SuspendHotkeysKey=Enter
;--------------------------------------------------
[Settings]
HotkeyEditMode=0
EditBoxesAvailable=0
;----------
ResizeModule=0
;----------
CheckforUpdatesDaily=1
CheckforupdatesWeekly=0
NeverCheckForUpdates=0
NeedUpdate=1
LastUpdateCheckTimeStamp=20250716202903
;--------------------------------------------------
[PaceProperties]
ScrlUpCount=33
ScrlUpInterval=150
ScrlDownCount=33
ScrlDownInterval=150
ScrlUpYes=1
ScrlUpNo=0
ScrlDownYes=0
ScrlDownNo=1
;--------------------------------------------------
[SavedHotkey]
KbAutoRunHotkey=r
PatternClickerHotkey=Shift
;----------
JumpHotkey0=Numpad0
JumpHotkey1=Numpad1
JumpHotkey2=Numpad2
JumpHotkey3=Numpad3
JumpHotkey4=Numpad4
;----------
QuickAccessHk1=1
QuickAccessHk2=2
QuickAccessHk3=3
QuickAccessHk4=4
QuickAccessHk5=5
QuickAccessHk6=6
QuickAccessHk7=7
QuickAccessHk8=8
QuickAccessHk9=9
;--------------------------------------------------
[AutoRun]
SprintKey=Shift
ForwardKey=w
;---------- Pseudo Hotkey (works similar to a hotkey)
SelectedButton=ButtonRT
ControllerKey=Joy1
;--------------------------------------------------
[QuickAccessPath]
QuickAccess1=https://fdj-software.gitbook.io/apps
QuickAccess2=https://cornucopias.io/
QuickAccess3=C:\Users\
QuickAccess4=https://outlook.live.com/mail/
QuickAccess5=https://drive.google.com/drive/
QuickAccess6=
QuickAccess7=
QuickAccess8=
QuickAccess9=
;--------------------------------------------------
[QuickAccessIcons]
QuickIcon1=
QuickIcon2=
QuickIcon3=
QuickIcon4=
QuickIcon5=
QuickIcon6=
QuickIcon7=
QuickIcon8=
QuickIcon9=
;--------------------------------------------------
[JumpProperties]
VeryShortJumpRace=400
VeryShortJumpLenght=500
;----------
ShortJumpRace=550
ShortJumpLenght=500
;----------
NormalJumpRace=550
NormalJumpLenght=600
;----------
LongJumpRace=550
LongJumpLenght=700
;----------
VeryLongJumpRace=600
VeryLongJumpLenght=750
;--------------------------------------------------
[AutoClicker]
ClickInterval=50
RandomOffset=50
;--------------------------------------------------
[CursorLocationClicker]
CoordX1=
CoordY1=
Coord1Interval=100
Radio1Yes=0
Radio1No=1
;----------
CoordX2=
CoordY2=
Coord2Interval=100
Radio2Yes=0
Radio2No=1
;----------
CoordX3=
CoordY3=
Coord3Interval=100
Radio3Yes=0
Radio3No=1
;----------
CoordX4=
CoordY4=
Coord4Interval=100
Radio4Yes=0
Radio4No=1
;----------
CoordX5=
CoordY5=
Coord5Interval=100
Radio5Yes=0
Radio5No=1
;----------
CoordX6=
CoordY6=
Coord6Interval=100
Radio6Yes=0
Radio6No=1
;----------
CoordX7=
CoordY7=
Coord7Interval=100
Radio7Yes=0
Radio7No=1
;----------
CoordX8=
CoordY8=
Coord8Interval=100
Radio8Yes=0
Radio8No=1
;----------
CoordX9=
CoordY9=
Coord9Interval=100
Radio9Yes=0
Radio9No=1
;----------
CoordX10=
CoordY10=
Coord10Interval=100
Radio10Yes=0
Radio10No=1
;----------
CoordX11=
CoordY11=
Coord11Interval=100
Radio11Yes=0
Radio11No=1
;----------
CoordX12=
CoordY12=
Coord12Interval=100
Radio12Yes=0
Radio12No=1
;----------
CoordX13=
CoordY13=
Coord13Interval=100
Radio13Yes=0
Radio13No=1
;----------
CoordX14=
CoordY14=
Coord14Interval=100
Radio14Yes=0
Radio14No=1
;----------
CoordX15=
CoordY15=
Coord15Interval=100
Radio15Yes=0
Radio15No=1
;----------
CoordX16=
CoordY16=
Coord16Interval=100
Radio16Yes=0
Radio16No=1
;----------
CoordX17=
CoordY17=
Coord17Interval=100
Radio17Yes=0
Radio17No=1
;----------
CoordX18=
CoordY18=
Coord18Interval=100
Radio18Yes=0
Radio18No=1
;----------
CoordX19=
CoordY19=
Coord19Interval=100
Radio19Yes=0
Radio19No=1
;----------
CoordX20=
CoordY20=
Coord20Interval=100
Radio20Yes=0
Radio20No=1
;----------
CoordX21=
CoordY21=
Coord21Interval=100
Radio21Yes=0
Radio21No=1
;----------
CoordX22=
CoordY22=
Coord22Interval=100
Radio22Yes=0
Radio22No=1
